import {
  faFacebook,
  faTwitter,
  faInstagram,
  faLinkedin,
  faYoutube,
  faSnapchat,
  faTiktok,
  faPinterest,
  faReddit,
  faGithub,
  faGitlab,
  faDribbble,
  faBehance,
  faTwitch,
  faDiscord,
  faMedium,
  faTelegram,
  faWhatsapp,
  faSlack,
  faStackOverflow,
  faVimeo,
  faWeibo
} from '@fortawesome/free-brands-svg-icons';

export const iconMap = {
  facebook: faFacebook,
  twitter: faTwitter,
  instagram: faInstagram,
  linkedin: faLinkedin,
  youtube: faYoutube,
  snapchat: faSnapchat,
  tiktok: faTiktok,
  pinterest: faPinterest,
  reddit: faReddit,
  github: faGithub,
  gitlab: faGitlab,
  dribbble: faDribbble,
  behance: faBehance,
  twitch: faTwitch,
  discord: faDiscord,
  medium: faMedium,
  telegram: faTelegram,
  whatsapp: faWhatsapp,
  slack: faSlack,
  stackoverflow: faStackOverflow,
  vimeo: faVimeo,
  weibo: faWeibo
};
