// src/utils/solidIcons.js

import {
  faPlus,
  faTrash,
  faEdit,
  faSave,
  faTimes,
  faCheck,
  faSearch,
  faDownload,
  faUpload,
  faEye,
  faEyeSlash,
  faUser,
  faLock,
  faSignOutAlt,
  faCog,
  faBell,
  faEnvelope,
  faHome,
  faInfoCircle,
  faExclamationTriangle,
  faCalendarAlt,
  faChevronDown,
  faChevronUp,
  faArrowRight,
  faArrowLeft,
  faFileAlt,
  faChartBar,
  faClock,
  faFileExport,
  faRotateLeft,
  faRotateRight,
  faImage,
  faSignInAlt,
  faQuestionCircle,
  faPhone,
  faBuilding,
  faGlobe,
  faFax,
  faList,
  faPrint,
  faCashRegister
} from '@fortawesome/free-solid-svg-icons';

export const solidIconMap = {
  plus: faPlus,
  trash: faTrash,
  edit: faEdit,
  save: faSave,
  times: faTimes,
  check: faCheck,
  search: faSearch,
  download: faDownload,
  upload: faUpload,
  eye: faEye,
  eyeslash: faEyeSlash,
  user: faUser,
  lock: faLock,
  signout: faSignOutAlt,
  cog: faCog,
  bell: faBell,
  envelope: faEnvelope,
  home: faHome,
  info: faInfoCircle,
  warning: faExclamationTriangle,
  calendar: faCalendarAlt,
  chevrondown: faChevronDown,
  chevronup: faChevronUp,
  arrowright: faArrowRight,
  arrowleft: faArrowLeft,
  file: faFileAlt,
  chart: faChartBar,
  clock: faClock,
  fileexport: faFileExport,
  rotateLeft: faRotateLeft,
  rotateRight: faRotateRight,
  image: faImage,
  signIn: faSignInAlt,
  questionCircle: faQuestionCircle,
  phone: faPhone,
  building: faBuilding,
  globe: faGlobe,
  list: faList,
  print: faPrint,
  cashRegister: faCashRegister
};
